version: '3'
services:
  nginx:
    container_name: nginx
    expose:
      - 1443
    ports:
      - "1443:443"
    volumes:
      - "./nginx/conf/:/etc/nginx/conf.d/:rw"
    networks:
      - frontend
    build:
      context: ./nginx
    restart: always
    command: [ nginx-debug, '-g', 'daemon off;' ]

  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - 5432
    networks:
      - backend
    volumes:
      - progresDB:/data/postgres
      - ./db/postgres.conf:/etc/postgresql/postgresql.conf
      - ./db/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    env_file:
      - ./.env

  rest-api:
    image: actix-postgres-threedee:latest
    expose:
      - 8000
    networks:
      - backend
      - frontend
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://admin:password123@postgres:5432/rust_sqlx?schema=public

  webclient:
    image: threedee-client
    networks:
      - frontend
    expose:
      - 80
    environment:
        ASPNETCORE_ENVIRONMENT: "Production"
        SERVICE: "http://rest-api/api"
        SECRET: ""

volumes:
  progresDB:

networks:
  backend:
  frontend: